// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfurtndfrvgxburrpvyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmdXJ0bmRmcnZneGJ1cnJwdnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyMzgxNjAsImV4cCI6MjEwNjgxNDE2MH0.91loZVDlqG4w4SqoEM2Lxr57aJ6nWZR9ODsYKOcQaQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});