// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htbozacrgnzvvtsuzhpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0Ym96YWNyZ256dnZ0c3V6aHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTUxOTQsImV4cCI6MjA2NTE5MTE5NH0.xbiaB3JumM6nFcTOrtoEyAlgF8KIB8dBwsmUwFvGcQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});